/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_96 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [7:0] outcmp
  );
  
  
  
  always @* begin
    outcmp[1+6-:7] = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        outcmp[0+0-:1] = z;
      end
      2'h2: begin
        outcmp[0+0-:1] = n ^ v;
      end
      2'h3: begin
        outcmp[0+0-:1] = z | (n ^ v);
      end
    endcase
  end
endmodule
