/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module stateCounter_4 (
    input clk,
    output reg inc_state
  );
  
  
  
  reg [23:0] M_stateCounter_d, M_stateCounter_q = 1'h0;
  
  always @* begin
    M_stateCounter_d = M_stateCounter_q;
    
    inc_state = 1'h0;
    M_stateCounter_d = M_stateCounter_q + 1'h1;
    if (M_stateCounter_q == 24'h989680) begin
      inc_state = 1'h1;
      M_stateCounter_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_stateCounter_q <= M_stateCounter_d;
  end
  
endmodule
